### PR TITLE
Fix test card scaling for different resolutions

### PR DESCRIPTION
**Pull request by johnboiles**
This fixes up the test card to support various resolutions now that @gxalpha added support in #149. At smaller resolutions the text is hidden.

640x480
image

1920x1080
image

### CODE REVIEW

**Comment by gxalpha** [comment]
Does it intentionally lack the text?

**Comment by johnboiles** [comment]
Yep, smaller resolutions I'm hiding the text. I could also poke around with sizing the fonts, but i think that adds too much complexity here. Most people are going to use 720p or above still I bet.

**Comment by johnboiles** [comment]
Luckily my PaintCode license hasn't expired yet and this is definitely non-commercial use. Let me know if there are any other changes you think I should make when I test it, since my trial time is limited!

**Comment by gxalpha** [comment]
I just noticed that the corner markers at the top right and bottom left don't quite reach the edge of the frame (Bottom left missed maybe 1 or 2 pixels to the left). I don't think this is intentional?
Bildschirmfoto 2020-05-28 um 22 32 06
Bildschirmfoto 2020-05-28 um 22 32 23

**Comment by johnboiles** [comment]
Good eye. I'll fix!

**Pull request merged**
