### PR TITLE
Try out macOS 10.13 to see if it just works

### PR DESCRIPTION
**Pull request by johnboiles**

### CODE REVIEW

**Comment by jasongrout** [comment]
It looks like OBS didn't compile. OBS itself supports High Sierra. How do they do it?

(I was also able to compile OBS on a High Sierra laptop.)

**Comment by johnboiles** [comment]
Did it actually fail or just stall somehow? Says it got to 100% Let me kick off the build again.

**Comment by jasongrout** [comment]
It might have just stalled.

It looks like OBS at least has access to a 10.13 box, not sure if it is used for builds: https://opencollective.com/obsproject/expenses/17742

**Comment by jasongrout** [comment]
> OBS itself supports High Sierra. How do they do it?

Interesting line: https://github.com/obsproject/obs-studio/blob/master/.github/workflows/main.yml#L124

```
cmake -DENABLE_SPARKLE_UPDATER=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11  ...
```

**Comment by jasongrout** [comment]
Good news! The artifacts that just built work great on my 10.13 laptop!

**Comment by johnboiles** [comment]
Awesome!!! So glad to hear it!

**Comment by johnboiles** [comment]
Rebasing since I made changes to the build in #97

**Comment by johnboiles** [comment]
I wonder if there are any practical differences using `CMAKE_OSX_DEPLOYMENT_TARGET`

**Comment by jasongrout** [comment]
Do you want me to test again, or do you think we are good?

**Comment by johnboiles** [comment]
I think we are good. Once this succeeds (and confirms I didn't break the build) I'll merge into master which will generate a pkg. I'd love it if you could test the pkg once that gets built.

Thanks for all your help on this!!

**Comment by jasongrout** [comment]
> I wonder if there are any practical differences using `CMAKE_OSX_DEPLOYMENT_TARGET`

I don't think so? https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by jasongrout** [comment]
And thank you for all you've done with this! It's really made my week.

**Comment by jasongrout** [comment]
> Interesting line: https://github.com/obsproject/obs-studio/blob/master/.github/workflows/main.yml#L124

This helps me feel like we aren't crazy to think that just setting that environment variable is all we really need to do to support older macOS versions.

**Comment by jasongrout** [comment]
Looks like the caching isn't working:

> Cache not found for input keys: obs-studio-25.0.8-macOS{{ env.MACOSX_DEPLOYMENT_TARGET }}.

And indeed, it is rebuilding instead of using the cache.

**Comment by johnboiles** [comment]
> caching isn't working

Yah just saw that too.

> This helps me feel like we aren't crazy to think that just setting that environment variable is all we really need to do to support older macOS versions.

Great idea to take a look at the OBS build process. Why didn't I think of that! :D

**Comment by jasongrout** [comment]
The pkg generated from merging this into master works great too. Thanks!

**Comment by johnboiles** [comment]
🎉 🎉 🎉

**Comment by dodgepong** [comment]
> Interesting line:

OBS would support older versions than High Sierra, but unfortunately we were forced to upgrade Qt to 5.14 which dropped support for everything before High Sierra. If you could get OBS working with an older version of Qt, then at least macOS 10.12 could be supported.

**Pull request merged**
