### PR TITLE
Bump resolution to 720p

### PR DESCRIPTION
**Pull request by gxalpha**
Let's discuss this xD

### CODE REVIEW

**Comment by gxalpha** [comment]
This breaks the program. For me, when trying to make a video with quicktime now, it crashes on clicking the "New video recording" (or however it is called in english). Same when opening photo booth.
To stop those programs from crashing, I even have to restart my mac.
I can give you the quicktime error log if it is helpful

**Comment by johnboiles** [comment]
Yeah thanks for taking a stab at this! Yeah I tried the same thing last night (~see branch [720p](https://github.com/johnboiles/obs-mac-virtualcam/tree/720p)~ nvm I see you used my branch :D).

Deleting the plugin (`sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin`) restored my apps to not crashing. Please go ahead and share your stack trace / log! It's probably the same as mine but I'd like to confirm.

As to _why_ this is: my best guess is that the plugin code has a framebuffer or other data storage that is allocated to a fixed length, and raising the resolution overflows that buffer. Or maybe it's possible there's a max size of data we can send via Mach IPC, and we would need to break this up into multiple messages.

One way to debug this is to build a second copy of OBS without the `.so` plugin installed in it, then rename its binary to something like `obs2`, then tell Xcode to attach the debugger to any process named `obs2`, then launch that copy of OBS `./obs2`. Then in that new copy of OBS, add the virtual camera as a source. Then you should be able to hit breakpoints in the plugin code. Super convoluted but at least allows you to step through things.

**Comment by gxalpha** [comment]
Here you go:
[QuickTime Player_2020-04-03-192654_Ebs-MacBook-Pro.crash.zip](https://github.com/johnboiles/obs-mac-virtualcam/files/4429547/QuickTime.Player_2020-04-03-192654_Ebs-MacBook-Pro.crash.zip)

**Comment by gxalpha** [comment]
ok also I wanted to test what you said and it turns out to be probable. I was successful changing it to 360p 16:9, so either I made something differently than what you did or your best guess seems very likely. 
If you are interested, [here] (https://github.com/gxalpha/obs-mac-virtualcam) are my changes

**Comment by johnboiles** [comment]
Oh wow, thank you for trying that! Really great data point!

I think i found my mistake. Seems to work but it's not easy to see the output resolution from QuickTime. Want to try as well?

**Comment by gxalpha** [comment]
Well you can record a video and check the resolution afterwards.
And for me it says 1280 × 720 pixels, so it works! Great progress!
(imo this could be merged into master now, that would help so that ppl don't get distracted by the weird distortions, maybe even make it usable for people who are confident enough to build their own obs and are really desperate searching for a solution)

**Pull request merged**
