### PR TITLE
Remove Compatibility, Contributing and Development

### PR DESCRIPTION
**Pull request by gxalpha**
Now that we have a wiki in my eyes we can remove those files. 
All links in Readme should now point to the wiki.

I'll still create this PR if anybody has a problem with the deletion of the files.

### CODE REVIEW

**Comment by fredemmott** [comment]
Just FYI, GitHub special-cases the CONTRIBUTING.md file, so there is some value in keeping it:

Screen Shot 2020-05-14 at 3 14 57 PM

**Comment by gxalpha** [comment]
Oh yeah, you're completely right!

**Comment by johnboiles** [comment]
Fine with me. Thanks for maintaining the documentation @gxalpha!

**Comment by johnboiles** [comment]
And good catch @fredemmott!

**Pull request merged**
