### PR TITLE
Make class names more unique to prevent namespace collisions

### LINKED ISSUE #232: [BUG]Virtual camera can't work with EOS Webcam Utility (Mac OSX Mojave)
Every time I installed this plugin, my OBS can't feed video capture from EOS Webcam utility. In order to get back video feed from EOS Webcam, I need to uninstall this plugin.

### PR DESCRIPTION
**Pull request by johnboiles**
Closes #232 and #215. Also corresponds to this change from @PatTheMav in the main OBS codebase.

Because ObjectiveC doesn't have namespacing, if any other plugin is loaded and has the same symbol names, one or both of the plugins may not work. This happened with the Canon EOS Webcam utility which appears to also be based off of [my code](https://github.com/johnboiles/coremediaio-dal-minimal-example).

This makes the namespaces more unique.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Just FYI - `MachServer` also needs to be namespaced, I missed that one in my PR.

**Comment by gxalpha** [comment]
Shall I create a PR? Or are you doing one?

**Comment by PatTheMav** [comment]
@gxalpha Go ahead, I'm swamped with CEF stuff right now.. 😂

**Comment by johnboiles** [comment]
Does it need to be namespaced just in case other OBS plugins use the naming `MachServer`?

**Comment by johnboiles** [comment]
@gxalpha if you wanted to knock that out, that'd be awesome!!

**Comment by PatTheMav** [comment]
True, in this specific case it interferes only with this plugin right here, true (because it's in the OBS plugin, not the DAL plugin). By that token it might be a non-issue once you archive this plugin.

**Comment by johnboiles** [comment]
Yeah def worth doing. It's more correct, can't hurt, and might avoid future issues.

**Pull request merged**
