### PR TITLE
Fix typo on Test Card

### LINKED ISSUE #209: [BUG] Mirrored Text on TestCard is spelled wrong
**Describe the bug**

The text says "Mirrorred" not "Mirrored".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by simoneves**
Closes #209

### CODE REVIEW

**Comment by simoneves** [comment]
To be clear, I haven't done a build to see if it looks correct (alignment etc.) as I don't have any dev tools on my new Mac yet, but hopefully it's correct!

**Comment by simoneves** [comment]
...although maybe with your CI system I don't need to, but can just download a packaged build for this branch when it's done?

**Comment by gxalpha** [comment]
Ok ill test it later, the CI unfortunately broke a few commits ago (and no one has gotten around to fixing them),
I'll report back

**Comment by simoneves** [comment]
OK thx

**Review by gxalpha — APPROVED** [review]
Tested, looks like its properly centered, see below
Bildschirmfoto 2020-09-17 um 16 55 03

**Comment by johnboiles** [comment]
Thank you @simoneves for the patch! Thank you @gxalpha as always for testing!

**Comment by simoneves** [comment]
@johnboiles You're welcome. I like fixes that only involve deleting code, especially if it's just deleting one character! ;)

**Pull request merged**
